### ISSUE TITLE
Table text in darkmode in black

### ISSUE THREAD

**Issue by puneethkanna** [devskrate/devskrate1.0#15]

**Comment by puneethkanna** [comment]
![Screenshot_2020-05-13 One Plus 8 pro - The Real Flagship](https://user-images.githubusercontent.com/40000406/81825326-247a2e80-9554-11ea-9718-fced0a54d642.png)

**Comment by puneethkanna** [comment]
Try to fix the css by using darkmode--activated class with table class.

**Comment by SriSatyaLokesh** [comment]
if fixed then close this issue

**Comment by puneethkanna** [comment]
Yes, it has been fixed!
